"""Update database schema to new structure

Revision ID: f3cb36ef8775
Revises: 
Create Date: 2024-07-13 19:36:51.998197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3cb36ef8775'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doorbell_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('image', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nfc_tag',
    sa.Column('nfc_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('nfc_id')
    )
    op.create_table('door_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nfc_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=150), nullable=False),
    sa.ForeignKeyConstraint(['nfc_id'], ['nfc_tag.nfc_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('log')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=150), nullable=False))
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.drop_column('nfc_tag')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nfc_tag', sa.VARCHAR(length=150), nullable=True))
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
        batch_op.drop_column('name')

    op.create_table('log',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('action', sa.VARCHAR(length=150), nullable=False),
    sa.Column('method', sa.VARCHAR(length=50), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('door_log')
    op.drop_table('nfc_tag')
    op.drop_table('doorbell_log')
    # ### end Alembic commands ###
